accounts/urls.py
from django.conf.urls import url,include

app_name = "accounts"

from .views import login_page,password_reset    , RegisterView, guest_register_view,logout_user,activate

urlpatterns = [
    # /service/ homepage with no extra information

    url(r'^login_user/$', login_page , name='login_user'),
    url(r'^logout/$', logout_user , name='logout_user'),
#    path(        'change-password/',   auth_views.PasswordChangeView.as_view(template_name='accounts/change-password.html'), ),

    url(r'^register/$', RegisterView, name='register'),
    url(r'^subscribe_us/$', guest_register_view, name='guest_register'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),

]

farmservice/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views

from accounts.views import login_page,password_reset,password_reset_done, RegisterView, guest_register_view,logout_user


urlpatterns = [
    # path('admin/', admin.site.urls),
    url('^admin/', admin.site.urls),
    url(r"^service/", include('service.urls', namespace='service')),
    url(r"^accounts/", include('accounts.urls', namespace='accounts')),

    url(r"^orders/", include('orders.urls', namespace='orders')),
    url(r'^$', views.main, name='main'),
    url('^', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
   urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
   urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

''' url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete')'''

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/(?P<pk>[0-9]+)/$', views.order_create, name='order_create'),
    url(r'^createcod/(?P<pk>[0-9]+)/$', views.order_create_cod, name='order_create_cod'),
    url(r'^order_created/$', views.order_created, name='order_created'),
    url(r'^handlerequest/$', views.handlerequest, name='handlerequest'),

    url(r'^your_order/$', views.your_order, name='your_order'),

    url(r'^delete/(?P<pk>[0-9]+)/$', views.delete_order, name='order_delete'),

]

service/urls.py
from django.conf.urls import url
from . import views

app_name = "service"

urlpatterns = [
    # /service/ homepage with no extra information
    url(r'^$', views.sfood, name="sfood"),

    url(r'^about_us$', views.about_us, name="about_us"),

    url(r'^contact_us$', views.contact_us, name="contact_us"),
    url(r'^services$', views.services, name="services"),

    url(r'^feedback_us/$', views.feedback, name='feedback'),

    # url(r'^test$', views.test,name="test"),

    # /service/ homepage with no extra information
    url(r'^vegetable$', views.Vindex, name="vegetables"),

    url(r'^sallon$', views.Findex, name="sallons"),

    url(r'^beverages$', views.Bindex, name="beverages"),
    url(r'^snacks$', views.Sindex, name="snacks"),


    url(r'^ref/$', views.ref, name="ref"),


    # /service/71(id)/ ^ represent the begning and $ ssign represent the end both at the same time
    url(r'^detail/(?P<album_id>[0-9]+)/$', views.detail, name="detail"),

    # /service/album/delete/
    # url(r'^album/(?P<pk>[0-9]+)/buy/$', views.Vindex, name='album-buy'),

    # /service/71(id)/ ^ represent the begning and $ ssign represent the end both at the same time

    # for registration

    # url(r'^carts/$', views.cart_home, name="cart"),
    # url(r'^carts/cart_update/$', views.cart_update, name="update"),

    url(r'^cart/$', views.cart_detail, name='cart_detail'),
    url(r'^cartdel/$', views.cart_del, name='cart_del'),
    url(r'^cart/add/(?P<product_id>[0-9]+)/$', views.cart_add, name='cart_add'),

    url(r'^cart/add_rem/(?P<product_id>[0-9]+)/$', views.cart_ar, name='cart_ar'),

    url(r'^cart/up/(?P<product_id>[0-9]+)/$', views.cart_up, name='cart_up'),

    url(r'^cart/remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

]

service/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import Permission
from django.db.models.signals import pre_save
from .utils import unique_slug_generator
from django.contrib.auth import get_user_model
from django import forms

User = get_user_model()

'''to craete  ne amodel maincatogorey first craete it and then makemigartions  and add it to the admi and then add ekemnts to it after add primary key in category and then ask for defulat 
 then give rimary key of your chice and migrate it fially   '''


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    nick_names = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=150,blank=True, unique=True ,db_index=True)
    logo=models.FileField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

   # class Meta:
   #     ordering = ('name', )
    #    verbose_name = 'category'
   #     verbose_name_plural = 'categories'

    def __str__(self):
        return self.name





  #  def get_absolute_url(self):
  #      return reverse('shop:product_list_by_category', args=[self.slug])



class Facility(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    icons = models.CharField(max_length=130, db_index=True)
    nick_names = models.CharField(max_length=100, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

   # class Meta:
   #     ordering = ('name', )
    #    verbose_name = 'category'
   #     verbose_name_plural = 'categories'

    def __str__(self):
        return self.name



class Shop(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=150, db_index=True)
    nick_names = models.CharField(max_length=100, db_index=True)
    description = models.TextField(blank=True)


    slug = models.SlugField(max_length=150,blank=True, unique=True ,db_index=True)
    time = models.CharField(max_length=50, db_index=True)
    maps = models.CharField(max_length=550, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    logo=models.FileField()
    available = models.BooleanField(default=True)
    premium = models.BooleanField(default=False)

    def __str__(self):
            return self.name



class SubCategory(models.Model):
    category = models.ForeignKey(Category  , on_delete=models.CASCADE)
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150,blank=True, unique=True ,db_index=True)
    shopcat = models.ForeignKey(Shop , on_delete=models.CASCADE)

    nick_names = models.CharField(max_length=100, db_index=True)
    logo=models.FileField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

   # class Meta:
   #     ordering = ('name', )
    #    verbose_name = 'category'
   #     verbose_name_plural = 'categories'

    def __str__(self):
        return '{}'.format(self.nick_names)


class Item(models.Model):
    category = models.ForeignKey(Category  , on_delete=models.CASCADE)
    name = models.CharField(max_length=150, db_index=True)
    nick_names = models.CharField(max_length=400, db_index=True)
    slug = models.SlugField(max_length=150, blank=True, unique=True, db_index=True)
    description = models.TextField(blank=True)
    city = models.CharField(max_length=15, db_index=True)
    available = models.BooleanField(default=True)
    logo = models.FileField()

    def __str__(self):
        return self.name



class Product(models.Model):
    user = models.ForeignKey(User  , on_delete=models.CASCADE)

    shops = models.ForeignKey(Shop , on_delete=models.CASCADE)
    subcat = models.ForeignKey(SubCategory , on_delete=models.CASCADE)

    prod=models.CharField(max_length=20, db_index=True)
    price = models.IntegerField()
    b_price=models.IntegerField()
    gram= models.CharField(max_length=20, db_index=True)
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True )
    updated_at = models.DateTimeField(auto_now=True)
    logo=models.FileField()

    #class Meta:
      #  ordering = ('name', )
     #   index_together = (('id', 'slug'),)

    def __str__(self):
        return '{}'.format(self.prod+'  '+ str(self.id))

#    def get_absolute_url(self):
    #    return reverse('shop:product_detail', args=[self.id, self.slug])


def shop_pre_save_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug= unique_slug_generator(instance)


pre_save.connect(shop_pre_save_receiver,sender=Shop)


def items_category_pre_save_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug= unique_slug_generator(instance)


pre_save.connect(items_category_pre_save_receiver,sender=Item)


def category_pre_save_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug= unique_slug_generator(instance)


pre_save.connect(category_pre_save_receiver,sender=Category)



def subcategory_pre_save_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug= unique_slug_generator(instance)


pre_save.connect(subcategory_pre_save_receiver,sender=SubCategory)

'''''
def product_pre_save_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug= unique_slug_generator(instance)


pre_save.connect(product_pre_save_receiver,sender=Product)

'''



class Feedback(models.Model):
    name= models.CharField(max_length=100)
    email = models.EmailField()
    sub= models.CharField(max_length=300)
    feedback = models.CharField(max_length=1000)

    update = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

service/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Feedback


#hair i wil do a shortcut that can be cahged furthere acccordign to need here iwill change quantity to one,

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 50)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class Feedbackform(forms.ModelForm):
    feedbacks = forms.CharField(widget=forms.Textarea, label="enter the feedback:")

    class Meta:
        model = Feedback

        fields = ['email', 'feedbacks']

service/templates/service/base.html
<!DOCTYPE HTML>
<html>

{% load staticfiles %}

	<head>


<!--product-->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">


{% block head %}

{% endblock %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Open+Sans">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  {% block basel %}

{% endblock %}


<style type="text/css">

div.b {
  text-align: left;
}
div.c {
  text-align: left;
}
div.d {
  text-align: left;
}

.fetse{
font-size: 50px;
    }

body {
	background: #e2eaef;
	font-family: "Open Sans", sans-serif;
}
h2 {
	color: #000;
	font-size: 26px;
	font-weight: 300;
	text-align: center;
	text-transform: uppercase;
	position: relative;
	margin: 30px 0 60px;
}


h2::after {
	content: "";
	width: 100px;
	position: absolute;
	margin: 0 auto;
	height: 4px;
	border-radius: 1px;
	background: #7ac400;
	left: 0;
	right: 0;
	bottom: -20px;
}

h2.sltxt::after {
	content: "";
	width: 100px;
	position: absolute;
	margin: 0 auto;
	height: 4px;
	border-radius: 1px;
	background: none;;
	left: 0;
	right: 0;
	bottom: -20px;
}

h2.sltxt{
text-decoration-line: none;
    }

h2.sltxt:after{
text-decoration-line: none;
    }


.carousel {
	margin: 50px auto;
	padding: 0 70px;
}
.carousel .item {
	color: #747d89;
	min-height: 325px;
    text-align: center;
	overflow: hidden;
}
.carousel .thumb-wrapper {
	padding: 25px 15px;
	background: #fff;
	border-radius: 6px;
	text-align: center;
	position: relative;
	box-shadow: 0 2px 3px rgba(0,0,0,0.2);
}
.carousel .item .img-box {
	height: 120px;
	margin-bottom: 20px;
	width: 100%;
	position: relative;
}
.carousel .item img {
	max-width: 100%;
	max-height: 100%;
	display: inline-block;
	position: absolute;
	bottom: 0;
	margin: 0 auto;
	left: 0;
	right: 0;
}
.carousel .item h4 {
	font-size: 18px;
}
.carousel .item h4, .carousel .item p, .carousel .item ul {
	margin-bottom: 5px;
}
.carousel .thumb-content .btn {
	color: #7ac400;
    font-size: 11px;
    text-transform: uppercase;
    font-weight: bold;
    background: none;
    border: 1px solid #7ac400;
    padding: 6px 14px;
    margin-top: 5px;
    line-height: 16px;
    border-radius: 20px;
}
.carousel .thumb-content .btn:hover, .carousel .thumb-content .btn:focus {
	color: #fff;
	background: #7ac400;
	box-shadow: none;
}
.carousel .thumb-content .btn i {
	font-size: 14px;
    font-weight: bold;
    margin-left: 5px;
}
.carousel .carousel-control {
	height: 44px;
	width: 40px;
	background: #7ac400;
    margin: auto 0;
    border-radius: 4px;
	opacity: 0.8;
}
.carousel .carousel-control:hover {
	background: #78bf00;
	opacity: 1;
}
.carousel .carousel-control i {
    font-size: 36px;
    position: absolute;
    top: 50%;
    display: inline-block;
    margin: -19px 0 0 0;
    z-index: 5;
    left: 0;
    right: 0;
    color: #fff;
	text-shadow: none;
    font-weight: bold;
}
.carousel .item-price {
	font-size: 13px;
	padding: 2px 0;
}
.carousel .item-price strike {
	opacity: 0.7;
	margin-right: 5px;
}
.carousel .carousel-control.left i {
	margin-left: -2px;
}
.carousel .carousel-control.right i {
	margin-right: -4px;
}
.carousel .carousel-indicators {
	bottom: -50px;
}
.carousel-indicators li, .carousel-indicators li.active {
	width: 10px;
	height: 10px;
	margin: 4px;
	border-radius: 50%;
	border: none;
}
.carousel-indicators li {
	background: rgba(0, 0, 0, 0.2);
}
.carousel-indicators li.active {
	background: rgba(0, 0, 0, 0.6);
}
.carousel .wish-icon {
	position: absolute;
	right: 10px;
	top: 10px;
	z-index: 99;
	cursor: pointer;
	font-size: 16px;
	color: #abb0b8;
}
.carousel .wish-icon .fa-heart {
	color: #ff6161;
}
.star-rating li {
	padding: 0;
}
.star-rating i {
	font-size: 14px;
	color: #ffc000;
}
</style>


<script type="text/javascript">
	$(document).ready(function(){
		$(".wish-icon i").click(function(){
			$(this).toggleClass("fa-heart fa-heart-o");
		});
	});
</script>


  <link rel="icon" href="{% static 'service/img/core-img/favicon.ico' %}">


	<link rel="stylesheet" href="{% static 'service/stylefarm.css' %}">



	</head>
	<body>

 <!-- Preloader -->
  <div class="preloader d-flex align-items-center justify-content-center">
    <div class="spinner"></div>
  </div>

  <!-- ##### Header Area Start ##### -->
  <header class="header-area">



    <!-- Navbar Area -->
    <div class="famie-main-menu">
      <div class="classy-nav-container breakpoint-off">
        <div class="container">
          <!-- Menu -->
          <nav class="classy-navbar justify-content-between" id="famieNav">
            <!-- Nav Brand -->
            <a href="{% url 'main' %}" class="nav-brand"><img src="{% static 'service/img/core-img/logo.png' %}" alt=""></a>
            <!-- Navbar Toggler -->
            <div class="classy-navbar-toggler">
              <span class="navbarToggler"><span></span><span></span><span></span></span>
            </div>
            <!-- Menu -->
            <div class="classy-menu">
              <!-- Close Button -->
              <div class="classycloseIcon">
                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
              </div>
              <!-- Navbar Start -->
              <div class="classynav">
                <ul>
                  <li class="active"><a href="{% url 'main'  %}">Home</a></li>

                <li><a href="{% url 'service:about_us'  %}">About</a></li>


                  <li><a href="{% url 'service:contact_us'  %}">Contact</a></li>
                  <li><a href="{% url 'service:cart_detail'  %}">Cart  <i class="icon_cart_alt" aria-hidden="true"></i></a></li>



								{% if user.is_authenticated %}
								<li>

                 			        <a href="{% url 'accounts:logout_user' %}">
                  			          <span class="" aria-hidden="true"></span>&nbsp; LogOut
                  			        </a>
                 				</li>

                  		      {% else %}
								<li class="has-dropdown">
									<a href="#">Log In</a>
									<ul class="dropdown">
										<li> <a href="{% url 'accounts:login_user' %}" class="button">&nbsp; LogIn</a></li>
										<li> <a href="{% url 'accounts:register' %}">

                                          </span>&nbsp; Sign Up</a></li>

									</ul>
								</li>
							{% endif %}

                </ul>

                <!-- Cart Icon -->
                <!--<div id="cartIcon">-->
                  <!--<a href="#">-->
                    <!--<i class="icon_cart_alt" aria-hidden="true"></i>-->
                    <!--<span class="cart-quantity">0</span>-->
                  <!--</a>-->
                <!--</div>-->
              </div>
              <!-- Navbar End -->
            </div>
          </nav>

          <!-- Search Form -->
          <div class="search-form">
            <form action="#" method="get">
              <input type="search" name="search" id="search" placeholder="Type keywords &amp; press enter...">
              <button type="submit" class="d-none"></button>
            </form>
            <!-- Close Icon -->
            <div class="closeIcon"><i class="fa fa-times" aria-hidden="true"></i></div>
          </div>
        </div>
      </div>
    </div>
  </header>



{% block body %}



{% endblock %}




  <!-- ##### Footer Area Start ##### -->
  <footer class="footer-area">
    <!-- Main Footer Area -->
    <div class="main-footer bg-img bg-overlay section-padding-80-0" style="background-image: url({% static 'service/img/bg-img/3.jpg' %});">

      <div class="container">
        <div class="row">

          <!-- Single Footer Widget Area -->
          <div class="col-12 col-sm-6 col-lg-3">
            <div class="footer-widget mb-80">
              <a href="#" class="foo-logo d-block mb-30"><img src="{% static 'service/img/core-img/logo11.png' %}" class="fml"></a>


            </div>
          </div>

            <div class="col-12 col-sm-6 col-lg-3">
      <div class="footer-widget mb-80">
              <div class="contact-info">
                  <h5 class="widget-title">FARMKET</h5>
                  <p>Farmket: The Complete. Need of the Farmer.</p>
                <p><i class="fa fa-map-pin" aria-hidden="true"></i>Cu ,CHANDIGARH</p>
                <p><i class="fa fa-envelope" aria-hidden="true"></i>info.farmket@gmail.com</p>
                <p><i class="fa fa-phone" aria-hidden="true"></i>798838xxxx</p>
              </div>
            </div>
        </div>

          <!-- Single Footer Widget Area -->
          <div class="col-12 col-sm-6 col-lg-3">
            <div class="footer-widget mb-80">
              <h5 class="widget-title">QUICK LINK</h5>
              <!-- Footer Widget Nav -->
              <nav class="footer-widget-nav">
                <ul>
                  <li><a href="{% url 'service:about_us' %}">About Us</a></li>
                  <li><a href="{% url 'service:contact_us' %}">Contact Us</a></li>
                  <!--<li><a href="#">Shipping</a></li>-->
                  <!--<li><a href="#">FAQs</a></li>-->
                  <!--<li><a href="#">Careers</a></li>-->
                  <!--<li><a href="#">Payments</a></li>-->
                  <!--<li><a href="#">Partners</a></li>-->
                  <!--<li><a href="#">Guide</a></li>-->
                  <!--<li><a href="#">Standard</a></li>-->
                  <!--<li><a href="#">News</a></li>-->
                  <!--<li><a href="#">Brands</a></li>-->
                </ul>
              </nav>
            </div>
          </div>



          <!-- Single Footer Widget Area -->
          <div class="col-12 col-sm-6 col-lg-3">
            <div class="footer-widget mb-80">
              <h5 class="widget-title">STAY CONNECTED</h5>
              <!-- Footer Social Info -->
              <div class="footer-social-info">
                <a href="#">
                  <i class="fa fa-facebook" aria-hidden="true"></i>
                  <span>Facebook</span>
                </a>
                <a href="#">
                  <i class="fa fa-instagram" aria-hidden="true"></i>
                  <span>Instagram</span>
                </a>
                <a href="#">
                  <i class="fa fa-pinterest" aria-hidden="true"></i>
                  <span>Pinterest</span>
                </a>
              </div>
            </div>
          </div>


      </div>
        </div>
    </div>

    <!-- Copywrite Area  -->
    <div class="copywrite-area">
      <div class="container">
        <div class="copywrite-text">
          <div class="row align-items-center">
            <div class="col-md-6">
              <p>
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Farmket
</p>
            </div>
            <div class="col-md-6">
              <div class="footer-nav">
                <nav>
                  <ul>
                    <li><a href="{% url 'service:about_us' %}">About</a></li>
                       <li><a href="{% url 'service:contact_us' %}">Contact</a></li>
                      <!--<li><a href="#">Login</a></li>-->

                  </ul>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- ##### Footer Area End ##### -->

  <!-- ##### All Javascript Files ##### -->
  <!-- jquery 2.2.4  -->
  <script src="{% static 'service/js/jquery.min.js' %}"></script>
  <!-- Popper js -->
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>


  <script src="{% static 'service/js/popper.min.js' %}"></script>
  <!-- Bootstrap js -->
  <script src="{% static 'service/js/bootstrap.min.js' %}"></script>
  <!-- Owl Carousel js -->
  <script src="{% static 'service/js/owl.carousel.min.js' %}"></script>
  <!-- Classynav -->
  <script src="{% static 'service/js/classynav.js' %}"></script>
  <!-- Wow js -->
  <script src="{% static 'service/js/wow.min.js' %}"></script>
  <!-- Sticky js -->
  <script src="{% static 'service/js/jquery.sticky.js' %}"></script>
  <!-- Magnific Popup js -->

  <!-- Scrollup js -->
  <script src="{% static 'service/js/jquery.scrollup.min.js' %}"></script>
  <!-- Jarallax js -->
  <script src="{% static 'service/js/jarallax.min.js' %}"></script>
  <!-- Jarallax Video js -->
  <script src="{% static 'service/js/jarallax-video.min.js' %}"></script>
  <!-- Active js -->
  <script src="{% static 'service/js/active.js' %}"></script>

 <!-- Owl Carousel js --><script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
{% block bases %}
{% endblock %}


	</body>
</html>

service/templates/service/feedback.html
{% extends 'service/base.html' %}
{% load static %}
{% block head %}

    <title>Farmket Feedback.</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" >
<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
<meta name="keywords" content="Feedback Us, feedback, connect,Your area valuable, online grocery farmket shopping, online grocery store,online supermarket,grocery sonipat,grocery narender nagar, online grocery shopping india, buy groceries online,online grocery  sonipat haryana sonipat  online vegetable store, service shopping online,Online Grocery roop nagar, online grocery sectore 1a">

<meta name="description" content="Your Feedback is valuable for us please give a feedback by which we can improve ourself . and provide more value to you.. Accoring to your needs. From  now in Sonipat">

<link rel="dns-prefetch" href="//www.googletagmanager.com">
<link rel="dns-prefetch" href="//www.google-analytics.com">
<link rel="canonical" href="http://www..com/service/feedback_us">

{% endblock %}


{% block body %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8">
                <h4 class="page-header">Feedback</h4>
                <form action="." method="post">
                    {% csrf_token %}
                    {{ form.as_p }}<br>

                    <input type="submit" class="btn btn-primary" value="send">
                </form>
            </div>
            <div class="col-md-4">
                <div class="page-header">
Your feedback is valuable                </div>



            </div>
        </div>
    </div>
{% endblock %}