accounts/urls.py
from django.conf.urls import url,include

app_name = "accounts"

from .views import login_page,password_reset    , RegisterView, guest_register_view,logout_user,activate

urlpatterns = [
    # /service/ homepage with no extra information

    url(r'^login_user/$', login_page , name='login_user'),
    url(r'^logout/$', logout_user , name='logout_user'),
#    path(        'change-password/',   auth_views.PasswordChangeView.as_view(template_name='accounts/change-password.html'), ),

    url(r'^register/$', RegisterView, name='register'),
    url(r'^subscribe_us/$', guest_register_view, name='guest_register'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),

]

farmservice/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views

from accounts.views import login_page,password_reset,password_reset_done, RegisterView, guest_register_view,logout_user


urlpatterns = [
    # path('admin/', admin.site.urls),
    url('^admin/', admin.site.urls),
    url(r"^service/", include('service.urls', namespace='service')),
    url(r"^accounts/", include('accounts.urls', namespace='accounts')),

    url(r"^orders/", include('orders.urls', namespace='orders')),
    url(r'^$', views.main, name='main'),
    url('^', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
   urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
   urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

''' url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete')'''

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/(?P<pk>[0-9]+)/$', views.order_create, name='order_create'),
    url(r'^createcod/(?P<pk>[0-9]+)/$', views.order_create_cod, name='order_create_cod'),
    url(r'^order_created/$', views.order_created, name='order_created'),
    url(r'^handlerequest/$', views.handlerequest, name='handlerequest'),

    url(r'^your_order/$', views.your_order, name='your_order'),

    url(r'^delete/(?P<pk>[0-9]+)/$', views.delete_order, name='order_delete'),

]

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField


User = get_user_model()


class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name', 'email',) #'full_name',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    #mos important to cahge password
    password = ReadOnlyPasswordHashField(
        label=("Password"),
        help_text=("Raw passwords are not stored, so there is no way to see "
                   "this user's password, but you can change the password "
                   "using <a href=\"../password/\">this form</a>."))

    class Meta:
        model = User
        fields = ('full_name', 'email','phone_no', 'password', 'is_active', 'is_admin')



    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class GuestForm(forms.Form):
    email    = forms.EmailField()


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email',widget=forms.EmailInput(attrs={'placeholder':'Email.'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Enter Password.'}),)


class RegisterForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    email = forms.EmailField(label='Email',widget=forms.EmailInput(attrs={'placeholder':'Email.'}))
    full_name = forms.CharField(label='Enter Name',widget=forms.TextInput(attrs={'placeholder':'Your Name.'}))
    phone_no = forms.IntegerField(label='Phone No.',widget=forms.TextInput(attrs={'placeholder':'Phone.'}))
  #  username = forms.CharField(label='username',widget=forms.TextInput(attrs={'placeholder':'Username'}))

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'placeholder':'Enter Password.'}),)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password.'}),)

    class Meta:
        model = User
        fields = ('full_name','phone_no','email') #'full_name',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        email= self.cleaned_data["email"]
        user.email=email.lower()
        # user.active = False # send confirmation email
        if commit:
            user.save()
        return user

accounts/views.py
from django.contrib.auth import authenticate, login, logout,get_user_model
from django.views.generic import CreateView, FormView
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.utils.http import is_safe_url
from django.http import HttpResponseRedirect
from django.core.mail import send_mail

from .forms import LoginForm, RegisterForm, GuestForm
from .models import GuestEmail

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import RegisterForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage
User = get_user_model()


def guest_register_view(request):
    form = GuestForm(request.POST or None)
    context = {
        "form": form
    }
    error_message=''
    next_ = request.GET.get('next')
    next_post = request.POST.get('next')
    redirect_path = next_ or next_post or None
    if request.method == "POST":
        email = request.POST.get("email")
        new_guest_email = GuestEmail.objects.create(email=email)
        request.session['guest_email_id'] = new_guest_email.id
        if is_safe_url(redirect_path, request.get_host()):
            return redirect(redirect_path)
        else:
            return redirect("/")

    return render(request, "accounts/login.html", {
        "form": form,
        "error_message": error_message,
        "connect":"Get connected to us"
    })


'''

class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = '/login_user/'

    def form_valid(self, form):
          #save the new user first
          form.save()
#          send_mail(
#              'Registered',
#              'Thanks for Registration with sniccy .',
#              'sniccyy@gmail.com',
#              ['ayushittechie@gmail.com'],
#              fail_silently=False,
#          )
          print("done   ")
          #get the username and password
          username = self.request.POST['email']
          password = self.request.POST['password1']
          #authenticate user then login
          user = authenticate(username=username, password=password)
          login(self.request, user)
          return redirect('/')
          
          

class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = '/login_user/'

    def form_valid(self, form):
          #save the new user first
          form.save()
#          send_mail(
#              'Registered',
#              'Thanks for Registration with sniccy .',
#              'sniccyy@gmail.com',
#              ['ayushittechie@gmail.com'],
#              fail_silently=False,
#          )
          print("done   ")
          #get the username and password
          username = self.request.POST['email']
          password = self.request.POST['password1']
          #authenticate user then login
          user = authenticate(username=username, password=password)
          login(self.request, user)
          user = form.save(commit=False)
          user.is_active = False
          user.save()
          current_site = get_current_site(self)
          print("site is beow")
          print(current_site)
          mail_subject = 'Activate your blog account.'
          message = render_to_string('acc_active_email.html', {
              'user': user,
              'domain': current_site.domain,
              'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
              'token': account_activation_token.make_token(user),
          })
          to_email = form.cleaned_data.get('email')
          email = EmailMessage(
              mail_subject, message, to=[to_email]
          )
          email.send()
          return HttpResponse('Please confirm your email address to complete the registration')
          #return redirect('/')

'''

def RegisterView(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            print(current_site)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('accounts/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form})

def password_reset():
    print()

def password_reset_done():
    print()

def logout_user(request):
    logout(request)
    form = LoginForm(request.POST or None)

    context = {
        "form": form,
    }
    return redirect('/accounts/login_user')



def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')




def login_page(request):
    form = LoginForm(request.POST or None)

    next_ = request.GET.get('next')
    next_post = request.POST.get('next')
    redirect_path = next_ or next_post or None

    if form.is_valid():
        email = form.cleaned_data.get("email")
        email=email.lower()
        password = form.cleaned_data.get("password")
        user = authenticate(request, email=email, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                try:
                    del request.session['guest_email_id']
                except:
                    pass
                if is_safe_url(redirect_path, request.get_host()):
                    return redirect(redirect_path)
                else:
                    return redirect("/")
            else:
                error_message = 'Invalid login'

        else:
            # Return an 'invalid login' error message.
            error_message = 'User not exists'

    else:
        return render(request, "accounts/login.html", {
            "form": form,
        })
    return render(request, "accounts/login.html", {
        "form": form,
        "error_message": error_message
    })

accounts/templates/accounts/acc_active_email.html
{% autoescape off %}
Hi {{ user.get_username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/base.html
<!DOCTYPE html>
    <html lang="en">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>Base Template</title>
        </head>
    <body>
      <div class='container'>
=    </div>


    </body>
  </html>

accounts/templates/accounts/login.html
    {% extends 'service/base.html' %}

{% load staticfiles %}
{% load crispy_forms_tags %}

    {% block head %}

    <title>farmket</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" >
<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">


	<link rel="stylesheet" href="{% static 'service/css/loginstyle.css' %}">
{% endblock %}



    {% block basel %}


    {% endblock %}




{% block albums_active %}active{% endblock %}


{% block body %}
<style>
	body{
	background-color:white;
	}
</style>


<div class="container h-100vh">
	<div class="row row h-100 align-items-center justify-content-centerr">
		<div class="col align-self-cente ">
			<div class="card">
				<div class="card-header text-center display-4">
					Log-In
				</div>
				<div class="card-body">

                        <form action="" method="POST">
							{% csrf_token %}

							<div class="row form-group" style="margin-top:40px;">
								<div class="col-md-12">
								            {{ form.email|as_crispy_field }}

								</div>

								<div class="col-md-12">
							            {{ form.password|as_crispy_field }}

									</div>
							</div>

						<div class="form-group">
							<a href="{% url 'accounts:register' %}" class="form-text text-muted">Don't Have a Account! Register</a>
							<a href="{% url 'password_reset' %}" class="form-text text-muted">Forgotten Password.</a>
						</div>

							<div class="form-group text-center">

						<button type="submit" class="btn  btn-lg btn-block">Login</button>
							</div>
						</form>

				</div>
			</div>
		</div>
	</div>
</div>

    {% endblock %}


    {% block bases %}

  <script src="{% static 'service/js/loginscript.js' %}"></script>

<script>
	bootstrapValidate('#email','email:Enter  avalid email addres');
</script>
{% endblock %}

accounts/templates/accounts/register.html
    {% extends 'service/base.html' %}

{% load staticfiles %}
{% load crispy_forms_tags %}

    {% block head %}

    <title>Register to .com to experince the better user experience,Help,Support about us, You can contact u s our email and phone no,We help You </title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" >
<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">


	<link rel="stylesheet" href="{% static 'service/css/loginstyle.css' %}">

{% endblock %}


    {% block basel %}


    {% endblock %}




{% block albums_active %}active{% endblock %}


{% block body %}




<div class="container h-100vh">
	<div class="row row h-100 align-items-center justify-content-centerr">
		<div class="col log align-self-cente ">
			<div class="card">
				<div class="card-header text-center display-4">
					Register
				</div>
				<div class="card-body">
   <form method="POST">
							{% csrf_token %}

							<div class="row form-group">
								<div class="col-md-12	 ">
								            {{ form.full_name|as_crispy_field }}

								</div>

								<div class="col-md-6	">
								            {{ form.phone_no|as_crispy_field }}

								</div>



                                <div class="col-md-6	">
																	            {{ form.email|as_crispy_field }}


								</div>

								<div class="col-md-6	">
								            {{ form.password1|as_crispy_field }}

								</div>


								<div class="col-md-6	">
							            {{ form.password2|as_crispy_field }}


									</div>
							</div>

						<div class="form-group">
							<a href="{% url 'accounts:login_user' %}" class="form-text text-muted"> Have a Account! Sign In</a>
						</div>
							<div class="form-group text-center">
						<button type="submit" class="btn  btn-lg btn-block">Register</button>
							</div>

						</form>				</div>
			</div>
		</div>
	</div>
</div>


    {% endblock %}


    {% block bases %}

  <script src="{% static 'service/js/loginscript.js' %}"></script>

<script>
	bootstrapValidate('#email','email:Enter  avalid email addres');
</script>
{% endblock %}