farmservice/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views

from accounts.views import login_page,password_reset,password_reset_done, RegisterView, guest_register_view,logout_user


urlpatterns = [
    # path('admin/', admin.site.urls),
    url('^admin/', admin.site.urls),
    url(r"^service/", include('service.urls', namespace='service')),
    url(r"^accounts/", include('accounts.urls', namespace='accounts')),

    url(r"^orders/", include('orders.urls', namespace='orders')),
    url(r'^$', views.main, name='main'),
    url('^', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
   urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
   urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

''' url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete')'''

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/(?P<pk>[0-9]+)/$', views.order_create, name='order_create'),
    url(r'^createcod/(?P<pk>[0-9]+)/$', views.order_create_cod, name='order_create_cod'),
    url(r'^order_created/$', views.order_created, name='order_created'),
    url(r'^handlerequest/$', views.handlerequest, name='handlerequest'),

    url(r'^your_order/$', views.your_order, name='your_order'),

    url(r'^delete/(?P<pk>[0-9]+)/$', views.delete_order, name='order_delete'),

]

service/urls.py
from django.conf.urls import url
from . import views

app_name = "service"

urlpatterns = [
    # /service/ homepage with no extra information
    url(r'^$', views.sfood, name="sfood"),

    url(r'^about_us$', views.about_us, name="about_us"),

    url(r'^contact_us$', views.contact_us, name="contact_us"),
    url(r'^services$', views.services, name="services"),

    url(r'^feedback_us/$', views.feedback, name='feedback'),

    # url(r'^test$', views.test,name="test"),

    # /service/ homepage with no extra information
    url(r'^vegetable$', views.Vindex, name="vegetables"),

    url(r'^sallon$', views.Findex, name="sallons"),

    url(r'^beverages$', views.Bindex, name="beverages"),
    url(r'^snacks$', views.Sindex, name="snacks"),


    url(r'^ref/$', views.ref, name="ref"),


    # /service/71(id)/ ^ represent the begning and $ ssign represent the end both at the same time
    url(r'^detail/(?P<album_id>[0-9]+)/$', views.detail, name="detail"),

    # /service/album/delete/
    # url(r'^album/(?P<pk>[0-9]+)/buy/$', views.Vindex, name='album-buy'),

    # /service/71(id)/ ^ represent the begning and $ ssign represent the end both at the same time

    # for registration

    # url(r'^carts/$', views.cart_home, name="cart"),
    # url(r'^carts/cart_update/$', views.cart_update, name="update"),

    url(r'^cart/$', views.cart_detail, name='cart_detail'),
    url(r'^cartdel/$', views.cart_del, name='cart_del'),
    url(r'^cart/add/(?P<product_id>[0-9]+)/$', views.cart_add, name='cart_add'),

    url(r'^cart/add_rem/(?P<product_id>[0-9]+)/$', views.cart_ar, name='cart_ar'),

    url(r'^cart/up/(?P<product_id>[0-9]+)/$', views.cart_up, name='cart_up'),

    url(r'^cart/remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

]

orders/models.py
from django.db import models
from service.models import Product,Shop
from django.contrib.auth import get_user_model

User = get_user_model()



class Order(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    o_id=models.CharField(max_length=10)
    name = models.CharField(max_length=60)
    addr = models.CharField(max_length=760)
    phone_no = models.CharField(max_length=11)
    shop=models.ForeignKey(Shop, on_delete=models.CASCADE)
    num= models.IntegerField()
    date=models.DateField()
    timing=models.CharField(max_length=60)

    total_a_cost=models.DecimalField(max_digits=15, default=22,decimal_places=2)
    total_cost=models.DecimalField(max_digits=15, default=22,decimal_places=2)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    total_i_price=models.DecimalField(max_digits=15, decimal_places=2)


    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

class OrderDis(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    total_dis = models.DecimalField(max_digits=10, decimal_places=2)#before price
    total_saved_rs = models.DecimalField(max_digits=10, decimal_places=2)#total aved rs in a order
    extra_dis=models.DecimalField(max_digits=15, decimal_places=2)


    def __str__(self):
        return '{}'.format(self.id)

orders/forms.py
from django import forms
from .models import Order

area = [
    ('','Select'),
    ('Narender nagar', 'Narender nagar'),
    ('Sector 1A', 'Sector 1'),
    ('Roop nagar', 'Roop nagar'),
    ('patel nagar', 'Patel nagar'),
]


class OrderCreateForm(forms.ModelForm):
   # s_area = forms.CharField(label='Select your local area:', widget=forms.Select(choices=area),initial=None)

    class Meta:
        model = Order
        fields = ['phone_no', 'addr','date','timing','num']

orders/views.py
from django.shortcuts import render,redirect
from .models import OrderItem,Order,OrderDis
from service.models import Shop
from .forms import OrderCreateForm
from service.cart import Cart
from django.contrib.auth.decorators import login_required
from orders.models import Order
from decimal import Decimal
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
#from random import random
import random
from random import choice
from string import ascii_lowercase
from django.views.decorators.csrf import csrf_exempt
from PayTm import Checksum
MERCHANT_KEY='f!zqdoLJqnR01wrz'

@login_required(login_url='/accounts/login_user')
def order_create(request, pk):
        cart = Cart(request)
        a=0

        oo=choice(ascii_lowercase)
        oo=oo.upper()
        print(oo.islower())
        print(choice(ascii_lowercase))

        print(random.randint(100, 999))
        print("hiiiii")
        for item in cart:
            a=a+1
        if a == 0:
            item=0
        order=0
        if a != 0:

            b = item
            ids = b['id']
            g = get_object_or_404(Shop, pk=int(ids))
            shopn=g.name
            print(g.name)

        if  a != 0 :
            a = sum(Decimal(item['price']) * 1 for item in cart.cart.values())
            b = sum(Decimal(item['b_price']) * 1 for item in cart.cart.values())
            nos = 1
            tshopc = nos * a
            s = (b - a) * nos

            if b == 0:
                p = 0

            else:
                p = round(Decimal(s / b * 100), 2)

            if request.method == 'POST':
                form = OrderCreateForm(request.POST)

          #      off=sum(Decimal(item['price']) * item['quantity'] for item in cart) - (
            #        sum(Decimal(item['price']) * item['quantity'] for item in cart)) / 10
           #     poff=cart.get_saved()+10
#                if form.is_valid():
                name = request.POST.get("name")
                pno = request.POST.get("pno")
                email = request.POST.get("addr")
                date = request.POST.get("date")
                time = request.POST.get("time")
                print(pno)
                print("pno")
                ordr = Order()
                ordr.addr = email
                ordr.user = request.user
                ordr.name = name
                ordr.phone_no = pno
                ordr.date = date
                ordr.timing = time
                ordr.num=nos
                print(pno)
                print(ordr.date)
                print(ordr.timing)
                print(ordr.addr)
                print(ordr.phone_no)

                #order = form.save()
                ordr.user=request.user
                ordr.total_cost=sum(Decimal(item['price']) * item['quantity'] for item in cart)

            #       z=(sum(Decimal(item['price']) * item['quantity'] for item in cart))/10   -z below
                ordr.total_a_cost=sum(Decimal(item['price']) * item['quantity'] for item in cart)

                ordr.shop=g
                print(g)
                ordr.save()
                print("abhit above")

                ordr.o_id=order_id(ordr)

                for item in cart:
                    OrderItem.objects.create(
                        order=ordr,
                        product=item['product'],
                        price=item['price'],
                        quantity=item['quantity'],
                        total_i_price=item['price']*item['quantity']
                    )

                ordr.save()
                cart.clear()

                print(ordr.name)
                param_dict={
                    'MID': 'oLhXxv07209903445994',
                    'ORDER_ID': str(ordr.o_id),
                    'TXN_AMOUNT':str(ordr.total_a_cost) ,
                    'CUST_ID': request.user.email,
                    'INDUSTRY_TYPE_ID': 'Retail',
                    'WEBSITE': 'WEBSTAGING',
                    'CHANNEL_ID': 'WEB',
                    'CALLBACK_URL':'http://127.0.0.1:8000/orders/handlerequest/'
                }
                param_dict['CHECKSUMHASH'] = Checksum.generate_checksum(param_dict, MERCHANT_KEY)

                #request paytm to tranfer teh amount to your account after payment by user
                #return render(request, 'orders/order/created.html', {'order': ordr})
                return render(request,'orders/order/paytm.html',{'param_dict':param_dict})

            else:
                form = OrderCreateForm()

            return render(request, 'orders/order/create.html', {'form': form,'shop':g,'shopc':tshopc,'no':nos})

        else:
            return redirect('/service/detail/'+pk+'/')


@login_required(login_url='/accounts/login_user')
def order_create_cod(request, pk):
        cart = Cart(request)
        a=0

        oo=choice(ascii_lowercase)
        oo=oo.upper()


        for item in cart:
            a=a+1
        if a == 0:
            item=0
        order=0
        if a != 0:

            b = item
            ids = b['id']
            g = get_object_or_404(Shop, pk=int(ids))

            shopn=g.name
            print(g.name)

        if  a != 0 :
            a = sum(Decimal(item['price']) * 1 for item in cart.cart.values())
            b = sum(Decimal(item['b_price']) * 1 for item in cart.cart.values())
            nos = 1
            tshopc = nos * a
            s = (b - a) * nos

            if b == 0:
                p = 0

            else:
                p = round(Decimal(s / b * 100), 2)

            if request.method == 'POST':
                form = OrderCreateForm(request.POST)

                name = request.POST.get("name")
                pno = request.POST.get('pno')
                email = request.POST.get("addr")
                date = request.POST.get("date")
                time = request.POST.get("time")
               # print(email+"before")
                print(request.user.email)
                print("pno")
                print(pno)


                ordr = Order()
                ordr.addr = email
                ordr.user = request.user
                ordr.name = name
                ordr.phone_no = pno
                ordr.date = date
                ordr.timing = time
                ordr.num=nos

                #order = form.save()
                ordr.user=request.user
                ordr.total_cost=sum(Decimal(item['b_price']) * item['quantity'] for item in cart)

            #       z=(sum(Decimal(item['price']) * item['quantity'] for item in cart))/10   -z below
                ordr.total_a_cost=sum(Decimal(item['price']) * item['quantity'] for item in cart)

                ordr.shop=g
                print(g)
                ordr.save()
                print("abhit above")

                ordr.o_id=order_id(ordr)

                for item in cart:
                    OrderItem.objects.create(
                        order=ordr,
                        product=item['product'],
                        price=(item['b_price']),
                        quantity=item['quantity'],
                        total_i_price=int(item['price']),
                    )
                cart.clear()

                ordr.save()

                return render(request, 'orders/order/created.html', {'order': ordr})


            else:
                form = OrderCreateForm()

            return render(request, 'orders/order/create.html', {'form': form,'shop':g,'shopc':tshopc,'no':nos})

        else:
            return redirect('/service/detail/'+pk+'/')



def order_id(order):
    id=order.id
    n=(order.name).lower()
    n=n[:1].lower()
    print(n)
    s1=choice(ascii_lowercase)
    s2=choice(ascii_lowercase)

    u=n[:1]
    if id < 10:
        print()
        ran= random.randint(100, 999)

    elif id >= 10 and id < 100 :
        ran= random.randint(10, 99)

    elif id >= 100 and id < 1000:
        ran= random.randint(1, 9)

    else:
        ran = 0

    if ran != 0:
        o_id=n+s1+str(id)+s2+str(ran)
    else:
        o_id=n+s1+str(id)+s2+str(ran)

    print(o_id)
    print("ayush above")
    return o_id

def delete_order(request, pk):
   #album = get_object_or_404(Album, pk=album_id)
    order = Order.objects.get(pk=pk)
    if order.paid == True:
        print("paid")
    else:
        order.delete()

    return redirect('orders:your_order')


# return render(request, 'orders/order/your_order.html', {'orders': orders, 'order_items': order_items})


@login_required(login_url='/login_user')
def your_order(request):
    orders = Order.objects.filter(user=request.user)

    order_items=OrderItem.objects.all()

    order_dis=OrderItem.objects.all()
    return render(request,'orders/order/your_order.html', {'orders':orders,'order_dis':order_dis})

@login_required(login_url='/login_user')
def order_created(request):
    return render(request, 'orders/order/created.html')


'''
                    OrderDis.objects.create(
                        order=order,
                        name='10%_discount',
                        total_dis=p+10,
                        total_saved_rs=cart.get_t_saved_rs(),
                        extra_dis=z,
                    )
'''
@csrf_exempt
def handlerequest(request):
#paytm will send post request
    form=request.POST
    response_dict={}
    verify=False
    checksum=0
    for i in form.keys():
        response_dict[i]=form[i]
        if i == 'CHECKSUMHASH':
            checksum=form[i]
    if checksum == 0:
        return redirect("/")

    verify=Checksum.verify_checksum(response_dict,MERCHANT_KEY,checksum)
    if verify:
        if response_dict['RESPCODE'] == '01':
            print('order Succesful')
            order = Order.objects.get(o_id=response_dict['ORDERID'])
            order.paid= True
            order.save()
            print("order id is")
            print(response_dict['ORDERID'])
        else:
            print("Not Succsefull")

orders/templates/orders/order/created.html
{% extends 'service/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}


{% block head %}

    <title>Fruits ,vegetables, Groceries,snacks ,beverages,sauce,and many more,at store</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" >
<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">

	<title>fARMKET Farmker Fullfill needs</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />

<link rel="dns-prefetch" href="//www.googletagmanager.com">
<link rel="dns-prefetch" href="//www.google-analytics.com">



{% endblock %}


{% block body %}
<div class="container" style="min-height:500px; margin-top:100px;">

			<div class="container">
				<div class="row">
					<div class="col-md-12">
			    <h2 class="page-header ">Thank You For Booking With Us
                </h2><br><br>
               <h3><b> <b >Your order has been successfully completed. Your order ID is <strong>{{ order.id }}{{ order.o_id }} {{ order.name }}

			   </strong>.<br> Order will Be Completed Soon. </b></b>
			   </h3>
					</div>
				</div>
			</div>
		</div>


{% endblock %}

orders/templates/orders/order/paymentstatus.html
{% extends 'service/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}


{% block head %}

    <title>Farmket.in Farmer Needs Booking Status.</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" >
<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">

	<title>Tour Template</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />

<link rel="dns-prefetch" href="//www.googletagmanager.com">
<link rel="dns-prefetch" href="//www.google-analytics.com">



{% endblock %}


{% block body %}

<div class="container" style="min-height:500px; margin-top:100px;">
    {% if response %}

    <div class="col-md-12">

        <h2>Payment status regarding your order Id {{response.ORDERID}}</h2>
       <h4> {% if response.RESPCODE == '01' %}
       Order Id: {{ response.ORDERID }}<br>
           Order  Paid<br>
       </h4><h3>   Total Amount Paid:{{ response.TXNAMOUNT }}<br><br>
        GatewayName:{{ response.GATEWAYNAME }}<br>
        DATE:{{ response.TXNDATE }}<br>
        ORDER SUCCESS
        {% else %}
        ORDER FAILURE
        {% endif%}
       </h3>
    </div>
{% endif %}
</div>
{% endblock %}
{% block js %}
<script>
     if(performance.navigation.type == 2){
  //location.reload();
  }
</script>
{% endblock %}

orders/templates/orders/order/paytm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Paytm merchant payment page</title>
</head>
<body>
<h1> Farmket. Redirecting you to the <Payment class="."></Payment></h1>
<h1>Please do not refresh your page....</h1>
<form action="https://securegw.paytm.in/order/process" method="post" name="paytm">
    {% for key, value in param_dict.items %}
    <input type="hidden" name="{{key}}" value="{{value}}">
    {% endfor %}


</form>
</body>
<script>
document.paytm.submit()
</script>
</html>

orders/templates/orders/order/your_order.html
{% extends 'service/base.html' %}
{% load static %}
{% block head %}

    <title></title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" >
<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
<meta name="keywords" content="Farmket">

<meta name="description" content="Farmket">


<link rel="dns-prefetch" href="//www.googletagmanager.com">
<link rel="dns-prefetch" href="//www.google-analytics.com">
<link rel="canonical" href="http://www..com/orders/your_order/">

{% endblock %}

{% block body %}

        {% if orders %}



<div class="container" style="min-height:500px;">
<div class="row" style="margin-top: 4%">
        <h2>Your Shopping orders

        </h2><hr>






    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
<h2>YOur  recent orders</h2>


{% for album in orders %}
             {% if not album.paid %}

  <div class="panel panel-default" style="border-radius:40px;">
    <div class="panel-heading" role="tab" id="a{{ album.id }}" style="padding:15px; border-radius:15px 15px 5px 5px;">
         <a role="button" data-toggle="collapse" data-parent="#accordion" href="#{{ album.id }}" aria-expanded="false" aria-controls="{{ album.id }}" >
      <h4 class="panel-title" style="color:black;">
          Id={{ album.id }} <span class="pull-right ">{{ album.created }}</span>
      </h4>
         </a>

    </div>
    <div id="{{ album.id }}" class="panel-collapse collapse " role="tabpanel" aria-labelledby="a{{ album.id }}">
      <div class="panel-body">

     <strong>     Name={{ album.first_name }} &nbsp<br>  Ordered At: {{ album.created }}
     </strong>

            <table class="table table-striped table-hover container">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Total Price</th>
                    </tr>
                </thead>
                <tbody>
{% for item in album.orderitem_set.all %}

                        <tr>

                            <td>{{ item.product }}</td>

                            <td>{{ item.quantity }}</td>


                            <td>{{ item.price }} rs/{{ item.weight }}</td>
                            <td>{{ item.total_i_price }} </td>

                        </tr>
                {% endfor %}

                </tbody>
            </table>


{% for dis in album.orderdis_set.all %}


                        Total Discount    {{ dis.total_dis }}% ||
          Total Rs Saved:     {{ dis.total_saved_rs }} rs

                {% endfor %}
                   <form action="{% url 'orders:order_delete' album.id %}" onSubmit="if(!confirm('Are you sure to Cancel Order..?')){return false;}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden"  name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm pull-right">
                                    <span class="glyphicon glyphicon-trash">CancelOrder</span>
                                </button>
                            </form>
<br>
<br>

<strong>          Total:{{ album.total_a_cost }}</strong>






      </div>
    </div>
  </div>
             {% endif %}
    {% endfor %}

</div>



        <div class="panel-group" id="accordion2" role="tablist" aria-multiselectable="true">
<h2>YOur Deleivered orders</h2>


{% for albumd in orders %}
             {% if  albumd.paid %}

  <div class="panel panel-default" style="border-radius:40px;">
    <div class="panel-heading" role="tab" id="a{{ albumd.id }}" style="padding:15px; border-radius:15px 15px 5px 5px;">
         <a role="button" data-toggle="collapse" data-parent="#accordion2" href="#{{ albumd.id }}" aria-expanded="false" aria-controls="{{ albumd.id }}" >
      <h4 class="panel-title" style="color:black;">
          Id={{ albumd.id }}  <span class="pull-right ">{{ albumd.created }}</span>
      </h4>
         </a>

    </div>
    <div id="{{ albumd.id }}" class="panel-collapse collapse " role="tabpanel" aria-labelledby="a{{ albumd.id }}">
      <div class="panel-body">


     <strong>      Ordered At: {{ albumd.created }} <br>Name={{ albumd.first_name }} &nbsp
     </strong>

            <table class="table table-striped table-hover container">
                <thead style="background-color: #5AC8FA">
                    <tr>
                           <th>Product</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Total Price</th>
                    </tr>
                </thead>
                <tbody>
{% for item in albumd.orderitem_set.all %}

                        <tr>

                            <td>{{ item.product }}</td>

                            <td>{{ item.quantity }}</td>


                            <td>{{ item.price }} rs</td>
                            <td>{{ item.total_i_price }} rs</td>

                        </tr>
                {% endfor %}

                </tbody>
            </table>

<strong>          Total:{{ albumd.total_cost }}</strong>

          <br>


      </div>
    </div>
  </div>
             {% endif %}
    {% endfor %}

</div>











    <p class="text-right">
            <a  href="{% url 'service:vegetables' %}" class="btn btn-default confirm">Continue Shopping</a>
                        <a href="{% url 'service:cart_detail' %}" class="btn btn-primary">My Cart</a>
<br>
<br>
        <a href="{% url 'service:feedback' %}" class="btn btn-primary">Give_feedback</a>

        </p>

  <div style="background-color: #5AC8FA">
                    <div colspan="3"></div>
      <div colspan="num" ><b><font size="15">User:{{ request.user }} </font></b></div>
    </div>


        </div>
    </div>


        {% for item in ialbum.orderitem_set.all %}

ayush

        {% endfor %}



        {% else %}
                <div class="container"  style="min-height:400px;">
                    <div class="row">
                <br>
                <a href="{% url 'main' %}">
                    <button type="button" class="btn btn-success" >
                        <span class="glyphicon glyphicon-shoping"></span>&nbsp; You have no Orders continue Shopping
                    </button>
                </a>
            </div>
            </div>





        {% endif %}

{% endblock %}

{% block bases %}
<script>
$(document).on('click', '.confirm_delete', function(){
  //  return confirm('Are you sure you want to delete this?');
    confirm("Press a button!");

})
</script>
{% endblock %}